config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', 
    omniauth_callbacks: 'users/omniauth_callbacks' }
  # admin routes
  get 'admin/' => 'admin/users#list'
  get 'admin/users' => 'admin/users#list'
  patch 'admin/users/:id/grand/:role' => 'admin/users#update'
  
  # root route
  root 'recipes#list'

  # recipe routes
  get 'recipes/list/:user_id' => 'recipes#specific_list', as: 'own_recipes'
  get 'recipes/list'
  post 'recipes/:id/rate' => 'recipes#rate'
  
  # ingredient routes
  get 'ingredients/new'
  get 'ingredients' => 'recipes#list'
  post 'ingredients' => 'ingredients#create'
  
  # category routes
  get 'categories/new'
  get 'categories' => 'recipes#list'
  post 'categories' => 'categories#create'
  
  # unit routes
  get 'units/new'
  get 'units' => 'recipes#list'
  post 'units' => 'units#create'
  
  # cookbook-entry routes
  get 'recipes/:id/add_to_cookbook' => 'cookbooks/entries#new'
  post 'cookbooks/:id/create_entry' => 'cookbooks/entries#create'
  delete 'cookbooks/entry/:id' => 'cookbooks/entries#destroy'
  
  # cookbook routes
  get 'cookbooks/new'
  get 'cookbooks/list', as: "cookbook_list"
  get 'cookbooks/:id/edit'=> "cookbooks#edit"
  get 'cookbooks/:id'=> "cookbooks#show", as: "cookbook"
  get 'cookbooks' => "cookbooks#list", as: "cookbooks"
  post 'cookbooks' => 'cookbooks#create'
  patch "cookbooks/:id" => "cookbooks#update"
  delete "cookbooks/:id" => "cookbooks#destroy"
  
  #search routes
  post 'search/search'
  post 'search/advanced_search'
  
  #meal_plans routes
  get 'meal_plans/' => 'meal_plans#week_overview'
  get 'meal_plans/new/' => 'meal_plans#new'
  get 'meal_plans/new/:date/:daytime' => 'meal_plans#new', as: 'new_meal_plan'
  post 'meal_plans/create'
  get 'meal_plans/update'
  get 'meal_plans/:date' => 'meal_plans#week_overview', as: 'meal_plans_week'
  get 'meal_plans/:id/edit' => 'meal_plans#edit', as: 'edit_meal_plan'
  get 'meal_plans/ingredient_requirements/:date' => 'meal_plans#ingredient_requirements', as: 'ingredient_requirement'
  get 'meal_plans/ingredient_requirements_pdf/:date' => 'meal_plans#ingredient_requirements_pdf', as: 'ingredient_requirement_pdf'
  
  patch 'meal_plan/:id' => 'meal_plans#update', as: 'meal_plan'
  post 'meal_plans' => 'meal_plans#create'  
  delete 'meal_plans/:id' => 'meal_plans#destroy', as: 'delete_meal_plan'
  
  #activity_plans routes
  get 'activity_plans/new'
  get 'activity_plans/new/:date' => 'activity_plans#new', as: 'new_activity_plan_week'
  get 'activity_plans/overview'

  get 'activity_plans/:date' => 'activity_plans#overview', as: 'activity_plans_week'
  
  post 'activity_plans' => 'activity_plans#create'
  
  get 'activity_plans/:id/edit' => 'activity_plans#edit'

  post 'activity_plans/create'
  delete 'activity_plans/:id' => 'activity_plans#destroy', as: 'delete_activity_plan'
  patch 'activity_plans/:id' => 'activity_plans#update'
  
  #activity routes
  get 'activities/new'
  post 'activities' => 'activities#create'
  
  #json routes
  get 'json/units'
  get 'json/categories'
  get 'json/ingredients'
  get 'json/activities'
  
  #comments routes
  get 'comments/new/:id' => 'comments#new'
  get 'comments/answer_to/:id' => 'comments#answer'
  get 'comments/:id/edit' => 'comments#edit'
  
  post 'comments' => 'comments#create'
  patch 'comments/:id' => 'comments#update'
  delete 'comments/:id' => 'comments#destroy'
  
  resources 'recipes'
#  get 'recipes' => 'recipes#list', as: 'recipes'
#  get 'recipes/new' => 'recipes#new'
#  get "recipes/:id/edit" => "recipes#edit", as: "edit_recipe"
#  get "recipes/:id" => "recipes#show", as: 'recipe'
#  delete "recipes/:id" => "recipes#destroy"
#  post 'recipes' => 'recipes#create'  
#  patch "recipes/:id" => "recipes#update"
  
end

app/models/meal_plan.rb
class MealPlan < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
  
  has_many :quantities, through: :recipe
  
  validates :date, presence: true
  validates :daytime, presence: true
  
  validates :user_id, presence: true #, numericality: { greater_than_or_equal: 0 }
  validates :recipe_id, presence: true #, numericality: { greater_than_or_equal: 0 }
  
  validates :daytime, inclusion: { in: %w(breakfast lunch dinner) }
  validates :date, uniqueness: { scope: [:daytime, :user_id] }
  
  validate :date, :meal_plan_may_not_be_in_past
    
  def meal_plan_may_not_be_in_past
    errors.add(:date, 'Cannot plan meals in the past.') unless self.date >= Date.today
  end
  
end

app/controllers/meal_plans_controller.rb
require 'prawn'
require 'open-uri'

class MealPlansController < ApplicationController
  
  def week_overview
    update_meal_plans_of_week
  end
  
  def new
    if params[:date]
      @meal_plan.date = params[:date]
    end
    
    if params[:daytime]
      @meal_plan.daytime = params[:daytime]
    end
  end

  def create
    if current_user.meal_plans << @meal_plan
      redirect_to meal_plans_path
    else
      render action: 'new'
    end
  end

  def destroy
    @meal_plan.destroy
    
    update_meal_plans_of_week
    
    render action: 'week_overview'
  end

  def edit
    
  end
  
  def update
    if @meal_plan.update_attributes(meal_plan_params)
      redirect_to meal_plans_path
    else
      render action: "edit"
    end
  end
  
  def ingredient_requirements
    update_meal_plans_of_week
    
    #    @quantities = @meal_plans.first.quantities
            
    @meal_plans.each do |m|
      @quantities = m.quantities unless @quantities
      @quantities.merge m.quantities
    end
    
    if @quantities
      @quantities = @quantities.group( :unit_id, :ingredient_id ).sum :quantity
    else
      @quantities = {}
    end
    
    @counts = @meal_plans.group( :recipe_id ).count
  end
    
  def ingredient_requirements_pdf
    update_meal_plans_of_week
    
    recipe_ids = @meal_plans.collect &:recipe_id 
    @recipes = Recipe.where ["id in (?)", recipe_ids]

#    @quantities = @meal_plans.first.quantities
        
    @meal_plans.each do |m|
      @quantities = m.quantities unless @quantities
      @quantities.merge m.quantities
    end
    
    @quantities = @quantities.group( :unit_id, :ingredient_id ).sum :quantity
    @counts = @meal_plans.group( :recipe_id ).count
           
    pdf = Prawn::Document.new 
    pdf.define_grid( columns: 6, rows: 10, gutter:10 )
    
    @quantities.each do |key, value|
      q = Quantity.find( key )[0]
      pdf.text "• #{value * @counts[q.recipe_id]}#{q.unit.name} #{q.ingredient.name}"
    end
    
    @recipes.each do |r|
      pdf.start_new_page
      
      pdf.grid([0, 0], [2, 2]).bounding_box do
        picture = r.pictures.first
        if picture  
          path = picture.picture_path 
        else 
          path = "app/assets/images/no_image.png"
        end
        
        pdf.image open( path ), fit: [pdf.bounds.width, pdf.bounds.height]
      end
      
      pdf.grid([0, 3], [2, 5]).bounding_box do
        pdf.text "<u>#{r.name}</u>", size: 16, inline_format: true
        pdf.move_down 5
        
        r.quantities.each do |q|
          pdf.text "#{ q.quantity }#{ q.unit.name } #{ q.ingredient.name }", overflow: :truncate
        end
      end
      
      pdf.grid([3, 0], [9, 5]).bounding_box do
        pdf.move_cursor_to pdf.bounds.top
          
        pdf.span pdf.bounds.width do
          pdf.text r.instructions
        end
      end
    end
    
    content = pdf.render
    
    MealPlanMailer.meal_week_plan( current_user, content ).deliver
    
    send_data content,
        :filename => "#{current_user.name}_shop_list.pdf",
        :type => "application/pdf"
    
#    render action: "ingredient_requirements"
  end
  
  private
    def meal_plan_params
      params.require( 'meal_plan' ).permit(:recipe_id, :date, :daytime)
    end
    
    def update_meal_plans_of_week
      if params[:date]
        d = Date.parse(params[:date])
      else
        d = Date.today
      end
      
      @week_start = d.beginning_of_week
      @week_end = @week_start.end_of_week
      @meal_plans = current_user.meal_plans.where("date <= '#{ @week_end }' and date >= '#{ @week_start }'")
    end
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
end

app/views/meal_plans/_daytime.html.erb
<tr>
	<td><p><%= header %></p></td>
	<% d = @week_start %>
	<% while d <= @week_end %>
		<% meal = @meal_plans.where "date = '#{ d }' and daytime = '#{ daytime }'" %>
		<% unless meal.empty? %>
			<p><%= render meal %></p>
		<%else %> 
		  <td>
		  	<%= link_to t('meal_plan.plan_meal'), new_meal_plan_path( d.to_s, daytime ) %>
		  </td>
		<% end %>
		<% d = d.tomorrow %>
	<% end %>
</tr>

app/views/meal_plans/_meal_plan.html.erb
<td>
	<%= link_to edit_meal_plan_path( meal_plan ) do %>
		<p><%= meal_plan.recipe.name %></p>
	<% end %>
	
	<%= link_to delete_meal_plan_path(meal_plan), method: :delete do %>
		<p><%= t('meal_plan.remove') %></p>
	<% end %>
</td>

app/views/meal_plans/_meal_plan_form.html.erb
<%= bootstrap_form_for @meal_plan do |f| %>
	
	<%= f.select :recipe_id, visible_recipes.collect { |r| [ r.name, r.id ] }, prompt: true, label: t('meal_plan.planned_recipe') %>
	
	<%= render partial: 'date_picker', locals: {field_name: :date, :label => t('meal_plan.date'), form_helper: f } %>
	
	<%= f.select :daytime, ["breakfast", "lunch", "dinner"], prompt: true, label: t('meal_plan.daytime') %>
	
	<%= f.submit t('meal_plan.save')%>
<% end %>

app/views/meal_plans/create.html.erb
<h1>MealPlans#create</h1>
<p>Find me in app/views/meal_plans/create.html.erb</p>

app/views/meal_plans/destroy.html.erb
<h1>MealPlans#destroy</h1>
<p>Find me in app/views/meal_plans/destroy.html.erb</p>

app/views/meal_plans/edit.html.erb
<h1><%= t('meal_plan.update')%></h1>

<%= render 'meal_plan_form'%>

app/views/meal_plans/ingredient_requirements.html.erb
<% @quantities.each do |key, value|%>
	<% q = Quantity.find( key )[0] %>
	<p><%= "#{value * @counts[q.recipe_id]}#{q.unit.name} #{q.ingredient.name}" %></p>
<% end %>

<%= link_to t('meal_plan.export_as_pdf'), ingredient_requirement_pdf_path( @week_start.to_s ) %>

app/views/meal_plans/new.html.erb
<h1><%= t('meal_plan.new_entry') %></h1>

<%= render 'meal_plan_form'%>

app/views/meal_plans/update.html.erb
<h1>MealPlans#update</h1>
<p>Find me in app/views/meal_plans/update.html.erb</p>

app/views/meal_plans/week_overview.html.erb
<h1><%= t('meal_plan.week_overview_header')%></h1>

<table class="table" style="table-layout: fixed; width: 100%;">
	<tr>
		<th><p> </p></th>
		<% d = @week_start %>
		<th><%= d %><p><%= t('weekdays_short.monday')%></p></th>
		<% d = d.tomorrow %>
		<th><%= d %><p><%= t('weekdays_short.tuesday')%></p></th>
		<% d = d.tomorrow %>
		<th><%= d %><p><%= t('weekdays_short.wednesday')%></p></th>
		<% d = d.tomorrow %>
		<th><%= d %><p><%= t('weekdays_short.thursday')%></p></th>
		<% d = d.tomorrow %>
		<th><%= d %><p><%= t('weekdays_short.friday')%></p></th>
		<% d = d.tomorrow %>
		<th><%= d %><p><%= t('weekdays_short.saturday')%></p></th>
		<% d = d.tomorrow %>
		<th><%= d %><p><%= t('weekdays_short.sunday')%></p></th>
	</tr>
	
	<%= render partial: 'daytime', locals: { daytime: 'breakfast', header: t('meal_plan.breakfast') } %>
	<%= render partial: 'daytime', locals: { daytime: 'lunch', header: t('meal_plan.lunch') } %>
	<%= render partial: 'daytime', locals: { daytime: 'dinner', header: t('meal_plan.dinner') } %>
	
	<tr>
		<td></td>
		<% d = @week_start %>
		<% 7.times do %>
			<td>
				<%= "#{t( 'meal_plan.total_food_value' )} #{@meal_plans.where( date: d ).collect( &:recipe ).inject(0){ |sum, r| sum + (r.food_value || 0) } }"%>
				<% d = d.tomorrow %>
			</td>
		<% end %>		
	</tr>
	

</table>

<%= link_to t('meal_plan.previous'), meal_plans_week_path( @week_start.last_week.to_s ) %>
<%= link_to t('meal_plan.calculate_ingredients'), ingredient_requirement_path( @week_start.to_s ) %>
<%= link_to t('meal_plan.next'), meal_plans_week_path( @week_end.tomorrow.to_s ), style: 'float: right' %>

<!--<%= link_to 'Previous', "#{ meal_plans_path }/#{ @week_start.last_week }" %>
<%= link_to 'Calculate Ingredients needed.', "#{ ingredient_requirement_path ( @week_start ) }" %>
<%= link_to 'Next', "#{ meal_plans_path }/#{ @week_end.tomorrow }", style: 'float: right' %>
-->