config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', 
    omniauth_callbacks: 'users/omniauth_callbacks' }
  # admin routes
  get 'admin/' => 'admin/users#list'
  get 'admin/users' => 'admin/users#list'
  patch 'admin/users/:id/grand/:role' => 'admin/users#update'
  
  # root route
  root 'recipes#list'

  # recipe routes
  get 'recipes/list/:user_id' => 'recipes#specific_list', as: 'own_recipes'
  get 'recipes/list'
  post 'recipes/:id/rate' => 'recipes#rate'
  
  # ingredient routes
  get 'ingredients/new'
  get 'ingredients' => 'recipes#list'
  post 'ingredients' => 'ingredients#create'
  
  # category routes
  get 'categories/new'
  get 'categories' => 'recipes#list'
  post 'categories' => 'categories#create'
  
  # unit routes
  get 'units/new'
  get 'units' => 'recipes#list'
  post 'units' => 'units#create'
  
  # cookbook-entry routes
  get 'recipes/:id/add_to_cookbook' => 'cookbooks/entries#new'
  post 'cookbooks/:id/create_entry' => 'cookbooks/entries#create'
  delete 'cookbooks/entry/:id' => 'cookbooks/entries#destroy'
  
  # cookbook routes
  get 'cookbooks/new'
  get 'cookbooks/list', as: "cookbook_list"
  get 'cookbooks/:id/edit'=> "cookbooks#edit"
  get 'cookbooks/:id'=> "cookbooks#show", as: "cookbook"
  get 'cookbooks' => "cookbooks#list", as: "cookbooks"
  post 'cookbooks' => 'cookbooks#create'
  patch "cookbooks/:id" => "cookbooks#update"
  delete "cookbooks/:id" => "cookbooks#destroy"
  
  #search routes
  post 'search/search'
  post 'search/advanced_search'
  
  #meal_plans routes
  get 'meal_plans/' => 'meal_plans#week_overview'
  get 'meal_plans/new/' => 'meal_plans#new'
  get 'meal_plans/new/:date/:daytime' => 'meal_plans#new', as: 'new_meal_plan'
  post 'meal_plans/create'
  get 'meal_plans/update'
  get 'meal_plans/:date' => 'meal_plans#week_overview', as: 'meal_plans_week'
  get 'meal_plans/:id/edit' => 'meal_plans#edit', as: 'edit_meal_plan'
  get 'meal_plans/ingredient_requirements/:date' => 'meal_plans#ingredient_requirements', as: 'ingredient_requirement'
  get 'meal_plans/ingredient_requirements_pdf/:date' => 'meal_plans#ingredient_requirements_pdf', as: 'ingredient_requirement_pdf'
  
  patch 'meal_plan/:id' => 'meal_plans#update', as: 'meal_plan'
  post 'meal_plans' => 'meal_plans#create'  
  delete 'meal_plans/:id' => 'meal_plans#destroy', as: 'delete_meal_plan'
  
  #activity_plans routes
  get 'activity_plans/new'
  get 'activity_plans/new/:date' => 'activity_plans#new', as: 'new_activity_plan_week'
  get 'activity_plans/overview'

  get 'activity_plans/:date' => 'activity_plans#overview', as: 'activity_plans_week'
  
  post 'activity_plans' => 'activity_plans#create'
  
  get 'activity_plans/:id/edit' => 'activity_plans#edit'

  post 'activity_plans/create'
  delete 'activity_plans/:id' => 'activity_plans#destroy', as: 'delete_activity_plan'
  patch 'activity_plans/:id' => 'activity_plans#update'
  
  #activity routes
  get 'activities/new'
  post 'activities' => 'activities#create'
  
  #json routes
  get 'json/units'
  get 'json/categories'
  get 'json/ingredients'
  get 'json/activities'
  
  #comments routes
  get 'comments/new/:id' => 'comments#new'
  get 'comments/answer_to/:id' => 'comments#answer'
  get 'comments/:id/edit' => 'comments#edit'
  
  post 'comments' => 'comments#create'
  patch 'comments/:id' => 'comments#update'
  delete 'comments/:id' => 'comments#destroy'
  
  resources 'recipes'
#  get 'recipes' => 'recipes#list', as: 'recipes'
#  get 'recipes/new' => 'recipes#new'
#  get "recipes/:id/edit" => "recipes#edit", as: "edit_recipe"
#  get "recipes/:id" => "recipes#show", as: 'recipe'
#  delete "recipes/:id" => "recipes#destroy"
#  post 'recipes' => 'recipes#create'  
#  patch "recipes/:id" => "recipes#update"
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  fuzzily_searchable :name, :instructions
  
  
  belongs_to :user
  
  has_many :pictures, dependent: :destroy
  has_many :quantities, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :cookbooks, through: :cookbook_entries
  has_many :cookbook_entries, dependent: :destroy

  has_many :ingredients, through: :quantities 
  
  has_and_belongs_to_many :categories, autosave: true
  
  validates :name, presence: true
  validates :instructions, presence: true
  validates :number_of_portions, presence: true, numericality: { greater_than: 0 }
  validates :food_value, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :range, inclusion: {in: ['public', 'registrated', 'private']}
  
  accepts_nested_attributes_for :quantities, :categories, allow_destroy: true
  
  #aus zeitmangel noch nicht komplett
  #umrechnen in gleiche einheiten fehlt noch
  def foodvalue
    quantities = self.quantities
    foodvalue = 0
    
    quantities.each { |quantity|
      ingredient = quantity.ingredient
      foodvalue += quantity.quantity * (ingredient.kj / ingredient.default_quantity)
    }
    self.food_value = foodvalue / self.number_of_portions
  end
  
  def average_rating
    unless self.ratings.count == 0
      rating = self.ratings.sum(:rating) / self.ratings.count
    else
      rating = 0
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    redirect_to recipes_list_path
  end
  
  def list
  end
  
  def specific_list
    @user = User.find(params[:user_id])
    where = {range: ["public"]}
    
    if user_signed_in?
      unless current_user.id.to_s == params[:user_id]
        where = {range: ["public", "registrated"]}
      else
        where = {range: ["public", "registrated", "private"]}
      end 
    end
    @recipes = @user.recipes.where(where) 
  end
  
  def new
    @recipe.quantities.build
    @recipe.quantities.first.build_unit
    @recipe.categories.build
  end
  
  def show
  end
  
  def create
    unless params[:recipe][:category_ids].nil?
      params[:recipe][:category_ids].uniq!
    end
    @recipe.foodvalue
    if @recipe.save
      current_user.recipes << @recipe
      redirect_to recipes_path
    else
      render action: 'new'
    end
  end
  
  def update
    unless params[:recipe][:category_ids].nil?
      params[:recipe][:category_ids].uniq!
    end
    if @recipe.update_attributes(recipe_params)
      @recipe.foodvalue
      @recipe.save
      redirect_to recipes_path
    else
      render action: "edit"
    end
  end
  
  def destroy
    @recipe.destroy
   
    redirect_to recipes_url
  end
  
  def rate    
    @rating = Rating.find_or_initialize_by(user: current_user, recipe_id: params[:id])
    @rating.rating = params[:rating]
    if(@rating.save) 
      render text: "ok"
    else
      render text: "nok"
    end
  end
  
  def edit
#    @recipe = Recipe.find(params[:id])
  end
    
  private
    def recipe_params
      params.require( 'recipe' ).permit( 'name', 'instructions', 'prep_time', 'range', 'number_of_portions',
        category_ids: [],
        quantities_attributes: [:id, :quantity, 
          :unit_id,
          :ingredient_id,
          :_destroy
        ]
      )
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def back_to_list
    content_tag :p do
      link_to t("Back"), recipes_path
    end
  end
  
  def load_comments 
    @comments = @recipe.comments
    render 'comments/list'
  end
end

app/views/recipes/_my_rating.html.erb
  <div class="rating" style="right:0px; top: 30px; width: 350px; height: 30px; position: absolute;z-index: 1">
    <% r = recipe.ratings.find_by( user: current_user) %>
    <% unless(r.nil?); r = r.rating else r = 0 end%>
    <div id="my_rating" class="rating stars" style="float: right">
      <% i = 1 %>
      <% r.to_i.times do %>
        <span data-rating="<%= i %>" class="glyphicon glyphicon-star" style="font-size: 22px; margin-right: 5px"></span>
        <% i += 1 %>
      <% end %>
      <% (5 -r).to_i.times do %>
        <span data-rating="<%= i %>" class="glyphicon glyphicon-star-empty" style="font-size: 22px; margin-right: 5px"></span>
        <% i += 1 %>
      <% end %>
      <script>
        rate_buttons = $('span[data-rating]');
        rate_buttons.hover(function() {
          $(this).toggleClass('glyphicon-star-empty glyphicon-star');
        });
        rate_buttons.click(function() {
          console.log($(this).data('rating'));
          $.post('/recipes/' + <%= recipe.id %> + '/rate', {rating: $(this).data('rating')}, function() {
            location.reload();
          });
        });
      </script>
    </div>
    <div class="rating numbers" style="margin-right: 15px; float: right">
      <%= t('rating.my_rating') + " "%><br />
      <small>(<%= t('rating.click_to_rate')%>)</small>
    </div>
  </div>

app/views/recipes/_rating.html.erb
<div class="rating" style="right:0px; top: 0px; width: 500px; height: 30px; position: absolute;">
  <% rating = recipe.average_rating.round %>
  <div class="rating stars" style="float: right">
    <% rating.times do %>
      <span class="glyphicon glyphicon-star" style="font-size: 22px; margin-right: 5px"></span>
    <% end %>
    <% (5 -rating).times do %>
      <span class="glyphicon glyphicon-star-empty" style="font-size: 22px; margin-right: 5px"></span>
    <% end %>
  </div>
  <div class="rating numbers" style="margin-right: 15px; float: right">
    &#216:
    <%= recipe.average_rating.round(1) %>
    (<%= t('rating.user', num: recipe.ratings.count)%>)
  </div>
</div>

app/views/recipes/_recipe.html.erb
<li style="list-style-type: none; clear: both">
  <div class="well" style="display: flex; margin-top: 10px">
    <div class="col-sm-3">
      <% p = recipe.pictures.first %>
      <% if p then img = p.picture_path else img = "/assets/no_image.png" end %>
      <img src="<%= img %>" class="img-rounded img-thumbnail" style="width: 250px; height: 135px;" />
    </div>
    <div class="col-sm-9">
    	<div style="padding-left: 20px; flex-grow: 100; position: relative">
    	  <%= render partial: 'recipes/rating', locals: {recipe: recipe} %>
    		<h4><%= link_to recipe.name, recipe_path(recipe) %> <small>(<%= recipe.prep_time.to_s + " " + t('recipe.prep_time_unit') %>)</small></h4>
    		<br />
    		<%= recipe.instructions %> 
    	</div>
  	</div>
	</div>
</li>

app/views/recipes/_recipe_form.html.erb
<script>
  var recipe_form_helper = new recipe_form();
  recipe_form_helper.select2button();
</script>
<%= bootstrap_nested_form_for( @recipe, label_col: "col-sm-2", control_col: "col-sm-8", layout: :horizontal) do |r_f| %>
  <%= r_f.text_field :name, label: t('recipe.name') %>
  
  <%= render partial: 'recipe_form_for_categories', locals: {r_f: r_f}%>

	<%= r_f.number_field :prep_time, append: t("minutes"), placeholder: "20", label: t('recipe.prep_time')  %>
	<%= r_f.number_field :number_of_portions, placeholder: "2", label: t('recipe.number_of_portions') %>
	
	<%= render partial: 'recipe_form_for_quantities', locals: {r_f: r_f}%>
	
  <%= r_f.text_area :instructions, rows: 6, placeholder: "Please enter the introductions", label: t('recipe.instructions') %>
  <% checked = [@recipe.range == "public", @recipe.range == "registrated", @recipe.range == "private"] %>
  <% isdisabled = [@recipe.range == "public", @recipe.range == "public" || @recipe.range == "registrated", @recipe.range == "public" || @recipe.range == "registrated" || @recipe.range == "private" ] %>
  <% help_text = ""%>		
	<% unless checked[0] || checked[1] || checked[2] %>
		<% checked[2] = true %>
		<% isdisabled = [false, false, false] %>
	<% end %>
	<% unless isdisabled[0] && isdisabled[1] && isdisabled[2]%>
	   <% help_text = t('recipe.helptext')%>
  <% end %>
	<%= r_f.form_group :range, layout: :horizontal, control_col: "col-sm-8", label: { text: t('recipe.visibile_for') }, help: help_text do %>
		<%= r_f.radio_button :range, "public", label: t('recipe.all'), checked: checked[0], inline: true, disabled: isdisabled[0] %>
		<%= r_f.radio_button :range, "registrated", label: t('recipe.only_registrated_user'), checked: checked[1], inline: true, disabled: isdisabled[1] %>
		<%= r_f.radio_button :range, "private", label: t('recipe.only_me'), inline: true, checked: checked[2], disabled: isdisabled[2] %>
	<% end %>
  <%= r_f.submit t('recipe.submit'), class: "btn btn-success"%>
<% end %>

<%= render 'recipe_form_blueprints'%>

app/views/recipes/_recipe_form_blueprints.html.erb
<div data-blueprint="" id="category_field_blueprint" style="display: none">
  <div class="category" style="display: inline-block; float: left">
    <div class="input-group">
      <div class="input-group-btn">
        <%= link_to 'X', "#", :class => "btn btn-danger", onclick: 'javascript:recipe_form_helper.remove_category(this); return false;' %>
      </div>
      <select class="form-control" id="recipe_category_ids" name="recipe[category_ids][]" prompt="category" style="width: initial"></select>
    </div>
  </div>
</div>

app/views/recipes/_recipe_form_for_categories.html.erb
<%= r_f.form_group :categories, layout: :horizontal, label_col: "col-sm-0", control_col: "col-sm-11" do %>
  <label class="control-label col-sm-2" for="categories">
    <%= t('category.categories')%>
  </label>
  <div class="col-sm-9">
    <div class="categories">
    <% @recipe.categories.each do |category| %>
      <div class="category" style="display: inline-block; float: left">
        <div class="input-group">
          <div class="input-group-btn">
            <%= link_to 'X', "#", :class => "btn btn-danger", onclick: 'javascript:recipe_form_helper.remove_category(this); return false;' %>
          </div>
          <%= r_f.select_without_bootstrap :category_ids, Category.all.collect { |c| [c.name, c.id]}, {selected: category.id}, 
            prompt: 'category', name: 'recipe[category_ids][]', class: 'form-control', style: 'width: initial'%>
        </div>
      </div>
    <% end %>
    </div>
    <div class="btn-group" style="float: right; margin: 10px; 0px;">
      <%# r_f.link_to_add '', :categories, class: 'hide'%> <!-- Hidden anchor to create the new form part at the right position -->
      <%= link_to t('category.more'), "#", class: 'btn btn-xs btn-info', onclick: 'javascript:recipe_form_helper.add_category(this); return false;'%> <!-- button to click on the hidden anchor with javascript -->
      <%= link_to t('category.new'), "#", :class => "btn btn-xs btn-success", onclick: 'javascript:recipe_form_helper.new_category(); return false;' %>
      <button class="btn btn-xs btn-default" disabled><%= t('category.category') %></button>
    </div>
  </div>
  <div style="display: none; clear:both"></div>
<% end %>

app/views/recipes/_recipe_form_for_quantities.html.erb
<%= r_f.form_group :quantities, layout: :horizontal, label_col: "col-sm-0", control_col: "col-sm-11" do %>
  <label class="control-label col-sm-2" for="ingredients">
    <%= t('ingredient.ingredients')%>
  </label>
  <div class="col-sm-9">
    <%= r_f.fields_for(:quantities) do |q_f| %>
      <div class="input-group col-sm-10" style="margin-bottom:5px">
        <div class="input-group-btn">
          <%= q_f.link_to_remove 'X', class: 'btn btn-danger' %>
        </div>    
        <%= q_f.number_field_without_bootstrap :quantity, placeholder: "5" , class: 'form-control col-sm-4'%>
        
        <div class="input-group-btn">
          <div class="btn-group">
            <%= render partial: "dropdown_button", locals: {name: "unit", show_name: t("unit.unit"), width: "75px"} %>
            <%= q_f.select_without_bootstrap :unit_id, Unit.all.collect { |u| [u.name, u.id]}, {}, prompt: 'unit', class: 'hide' %>
          </div>
          <div class="btn-group">
            <%= render partial: "dropdown_button", locals: {name: "ingredient", show_name: t("ingredient.ingredient"), width: "125px"} %>          
            <%= q_f.select_without_bootstrap :ingredient_id, Ingredient.all.collect { |i| [i.name, i.id]}, {}, prompt: 'ingredient', class: 'hide' %>
          </div>
        </div>
        <script>
          recipe_form_helper.initSelects('unit');
          recipe_form_helper.initSelects('ingredient');
        </script>
      </div>
    <% end %>
    <%= r_f.link_to_add '', :quantities, class: 'hide' %> <!-- Hidden anchor to create the new form part at the right position -->
    <div class="btn-group" style="float: right; margin: 10px; 0px;">
      <%= link_to t('ingredient.more'), "javascript:$('[data-association=\"quantities\"].hide.add_nested_fields').click()", class: 'btn btn-xs btn-info'%> <!-- button to click on the hidden anchor with javascript -->
      <%= link_to t('ingredient.new'), "javascript:recipe_form_helper.new_ingredient();", :class => "btn btn-xs btn-success" %>
      <button class="btn btn-xs btn-default" disabled><%= t('ingredient.ingredient') %></button>
    </div>
    <div class="btn-group" style="float: right; margin: 10px; 0px;">
      <%= link_to t('unit.new'), "javascript:recipe_form_helper.new_unit();", :class => "btn btn-xs btn-success" %>
      <button class="btn btn-xs btn-default" disabled><%= t('unit.unit') %></button>
    </div>
  </div>
  <div style="display: none; clear:both"></div>
<% end %>
	

app/views/recipes/edit.html.erb
<h2> Ändere Rezept </h2>
<div class="well" style="display: block;">
  <%= render 'recipe_form'%>
</div>

app/views/recipes/list.html.erb
<h1><%= @headline || t('recipe.list_of_all_recipes') %></h1>
<ul>
	<%= render @recipes%>
</ul>

app/views/recipes/new.html.erb
<h2><%= t('recipe.new_recipe')%></h2>
<div class="well" style="display: block;">
  <%= render 'recipe_form'%>
</div>

app/views/recipes/recipes.html.erb
<h1>Recipes#recipes</h1>
<p>Find me in app/views/recipes/recipes.html.erb</p>

<ul>
	<%= render @recipes%>
</ul>

app/views/recipes/show.html.erb
<script>
  var recipe_helper = new recipe();
</script>

<h2><%= t('recipe.details_for')%>
  <%= @recipe.name%> 
  <small>
    <% unless @recipe.prep_time.nil? %>
      (<%= @recipe.prep_time.to_s + " " + t('recipe.prep_time_unit')%>)
    <% end %>
  </small>
  <div style = "float: right; font-size: 14px"><%= t('recipe.autor') + ": " + @recipe.user.name%></div>
</h2>
<% if user_signed_in?%>
  <% if current_user.id == @recipe.user_id%>
    <% if(@recipe.range == "private")%>
      <%= link_to t("delete"), @recipe, data: { confirm: t('recipe.delete_popup', recipe: @recipe.name) }, method: :delete %>
    <% end%>
    <%= link_to t("change"), edit_recipe_path(@recipe) %>
  <% end %>
  <%= link_to t("recipe.add_to_cookbook"), 'javascript:recipe_helper.add_to_cookbooks();' %>
<% end %>
<div class="well" style="display: flex; margin-top: 10px">
  <% p = @recipe.pictures.first %>
  <% if p then img = p.picture_path else img = "/assets/no_image.png" end %>
  <img src="<%= img %>" class="img-rounded img-thumbnail" style="width: 250px; height: 135px;" />
  <div style="padding-left: 20px; flex-grow: 100; position: relative">

    <%= render partial: 'rating', locals: {recipe: @recipe} %>
    <%= render partial: 'my_rating', locals: {recipe: @recipe} %>

    <h4>
      <%= t('ingredient.ingredients') + ' ' + t('for') + ' ' + @recipe.number_of_portions.to_s + ' ' + t('persons') + ':'%> <br/>      
    </h4>
		<% quantities = @recipe.quantities %>
		<%= render quantities %>
		<br />
		
    <h4>
  		<%= t('recipe.instructions') + ":"%><br />
    </h4>
		<%= @recipe.instructions %> 
	</div>
</div>

<%= load_comments %>

app/views/recipes/specific_list.html.erb
<h1><%= t('recipe.list_of_recipes_from')+ " " + @user.name %></h1>
<ul>
	<%= render @recipes%>
</ul>